[package]
name = "cfdkim"
version = "0.3.0"
authors = ["Sven Sauleau <sven@cloudflare.com>"]
edition = "2021"
description = "DKIM (RFC6376) implementation"
repository = "https://github.com/cloudflare/dkim"
documentation = "https://docs.rs/cfdkim"
categories = ["email"]
keywords = ["email", "dkim", "authentification"]
readme = "README.md"
license = "MIT"

[dependencies]
ed25519-dalek = "1.0.1"
mailparse = "0.14"
quick-error = "2.0.1"
nom = "7.1.0"
chrono = { version = "0.4.19", default-features = false, features = ["clock", "std"] }
trust-dns-resolver = "0.22"
futures = "0.3.18"
sha-1 = { version = "0.10", features = ["oid"] }
sha2 = { version = "0.10", features = ["oid"] }
base64 = "0.21.0"
rsa = "0.8"
slog = "2.7.0"
indexmap = "1.8.0"

[dev-dependencies]
tokio = { version = "1.20", features = ["macros"] }
regex = "1"
